# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1008, 895)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.browser.setGeometry(QtCore.QRect(635, 750, 321, 81))
        self.browser.setObjectName("browser")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(430, 750, 91, 25))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_button.setIcon(icon)
        self.stop_button.setObjectName("stop_button")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(240, 750, 91, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_button.setIcon(icon1)
        self.start_button.setObjectName("start_button")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(60, 740, 61, 61))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/images/jderobot.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 400, 881, 301))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image = QtWidgets.QLabel(self.layoutWidget)
        self.image.setObjectName("image")
        self.horizontalLayout.addWidget(self.image)
        self.imageFiltered = QtWidgets.QLabel(self.layoutWidget)
        self.imageFiltered.setObjectName("imageFiltered")
        self.horizontalLayout.addWidget(self.imageFiltered)
        self.start_button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.start_button_2.setGeometry(QtCore.QRect(320, 30, 51, 51))
        self.start_button_2.setAutoFillBackground(False)
        self.start_button_2.setText("")
        self.start_button_2.setIcon(icon1)
        self.start_button_2.setIconSize(QtCore.QSize(32, 32))
        self.start_button_2.setObjectName("start_button_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 800, 201, 25))
        self.pushButton.setObjectName("pushButton")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 20, 171, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.forwardkinematic = QtWidgets.QComboBox(self.centralwidget)
        self.forwardkinematic.setGeometry(QtCore.QRect(30, 50, 201, 31))
        self.forwardkinematic.setObjectName("forwardkinematic")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(560, 20, 171, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.inversekinematic = QtWidgets.QComboBox(self.centralwidget)
        self.inversekinematic.setGeometry(QtCore.QRect(560, 50, 201, 31))
        self.inversekinematic.setObjectName("inversekinematic")
        self.start_button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.start_button_3.setGeometry(QtCore.QRect(850, 30, 51, 51))
        self.start_button_3.setAutoFillBackground(False)
        self.start_button_3.setText("")
        self.start_button_3.setIcon(icon1)
        self.start_button_3.setIconSize(QtCore.QSize(32, 32))
        self.start_button_3.setObjectName("start_button_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 100, 371, 271))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(22)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.jointSlider_1 = QtWidgets.QSlider(self.layoutWidget1)
        self.jointSlider_1.setOrientation(QtCore.Qt.Horizontal)
        self.jointSlider_1.setObjectName("jointSlider_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.jointSlider_1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.jointSlider_2 = QtWidgets.QSlider(self.layoutWidget1)
        self.jointSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.jointSlider_2.setObjectName("jointSlider_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.jointSlider_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.jointSlider_3 = QtWidgets.QSlider(self.layoutWidget1)
        self.jointSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.jointSlider_3.setObjectName("jointSlider_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.jointSlider_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.jointSlider_4 = QtWidgets.QSlider(self.layoutWidget1)
        self.jointSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.jointSlider_4.setObjectName("jointSlider_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.jointSlider_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.jointSlider_5 = QtWidgets.QSlider(self.layoutWidget1)
        self.jointSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.jointSlider_5.setObjectName("jointSlider_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.jointSlider_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.jointSlider_6 = QtWidgets.QSlider(self.layoutWidget1)
        self.jointSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.jointSlider_6.setObjectName("jointSlider_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.jointSlider_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.gripperSlider = QtWidgets.QSlider(self.layoutWidget1)
        self.gripperSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gripperSlider.setObjectName("gripperSlider")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.gripperSlider)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(570, 100, 158, 271))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setHorizontalSpacing(10)
        self.formLayout_2.setVerticalSpacing(22)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.xEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.xEdit.setObjectName("xEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.xEdit)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.yEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.yEdit.setObjectName("yEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.yEdit)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.zEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.zEdit.setObjectName("zEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.zEdit)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.rollEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.rollEdit.setObjectName("rollEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rollEdit)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.pitchEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.pitchEdit.setObjectName("pitchEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pitchEdit)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.yawEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.yawEdit.setObjectName("yawEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.yawEdit)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(810, 140, 111, 162))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.planButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.planButton.setObjectName("planButton")
        self.verticalLayout.addWidget(self.planButton)
        self.executeButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.executeButton.setObjectName("executeButton")
        self.verticalLayout.addWidget(self.executeButton)
        self.planexeButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.planexeButton.setObjectName("planexeButton")
        self.verticalLayout.addWidget(self.planexeButton)
        self.stopexeButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.stopexeButton.setObjectName("stopexeButton")
        self.verticalLayout.addWidget(self.stopexeButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1008, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.image.setText(_translate("MainWindow", "TextLabel"))
        self.imageFiltered.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "Launch Rviz"))
        self.label_8.setText(_translate("MainWindow", "Forward Kinematic"))
        self.label_9.setText(_translate("MainWindow", "Inverse Kinematic"))
        self.label.setText(_translate("MainWindow", "Joint1"))
        self.label_2.setText(_translate("MainWindow", "Joint2"))
        self.label_3.setText(_translate("MainWindow", "Joint3"))
        self.label_4.setText(_translate("MainWindow", "Joint4"))
        self.label_5.setText(_translate("MainWindow", "Joint5"))
        self.label_6.setText(_translate("MainWindow", "Joint6"))
        self.label_7.setText(_translate("MainWindow", "Gripper"))
        self.label_10.setText(_translate("MainWindow", "x"))
        self.label_11.setText(_translate("MainWindow", "y"))
        self.label_12.setText(_translate("MainWindow", "z"))
        self.label_13.setText(_translate("MainWindow", "roll"))
        self.label_14.setText(_translate("MainWindow", "pitch"))
        self.label_15.setText(_translate("MainWindow", "yaw"))
        self.planButton.setText(_translate("MainWindow", "Plan"))
        self.executeButton.setText(_translate("MainWindow", "Execute"))
        self.planexeButton.setText(_translate("MainWindow", "Plan && Execute"))
        self.stopexeButton.setText(_translate("MainWindow", "Stop"))

import resources_rc
